name: Tests

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Setup Java"
        uses: "actions/setup-java@v3"
        with:
          distribution: "temurin"
          java-version: "19"

      - name: "Setup Clojure"
        uses: "DeLaGuardo/setup-clojure@master"
        with:
          cli: "latest"
          bb: "latest"

      - name: "Apply Cache"
        uses: "actions/cache@v3"
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: "todos-${{ hashFiles('deps.edn') }}"
          restore-keys: "$todos-"

      - name: "Run tests"
        run: "bb test"
